---
title: "Personal Statistics Report - Stories & Notes"
output:
  html_document: default
params:
  fpath: "C:/Users/briney/Documents/JobDocs/LibStats/Reports/data"
  periodStart: "2018-01-01 00:00:00"
  periodEnd: "2018-05-30 11:59:59"
  person: "kbowes" 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(stringr)
library(lubridate)
library(knitr)

  ## Set parameters -- CHANGE AS NECESSARY
  pStart <-  ymd_hms(params$periodStart)
  pEnd <-  ymd_hms(params$periodEnd)
  pers <- params$person 

  
  
  ## Load consultation data
  
  finput <- paste(params$fpath, "Cons.csv", sep="/")
  Cons_all <- read_csv(finput)
  
  Cons <- filter(Cons_all, Cons_all$StaffName==pers & Cons_all$ConsDate>=pStart & 
                   Cons_all$ConsDate<=pEnd)
  Cons <- add_column(Cons, Week=week(Cons$ConsDate))
  
  ## Load presentation data
  
  finput <- paste(params$fpath, "Pres.csv", sep="/")
  Pres_all <- read_csv(finput)
  
  Pres <- filter(Pres_all, Pres_all$StaffName==pers & Pres_all$PresDateTime>=pStart & 
                   Pres_all$PresDateTime<=pEnd)
  Pres <- add_column(Pres, Week=week(Pres$PresDateTime))
  
  ## Load transaction data
  
  finput <- paste(params$fpath, "Trans.csv", sep="/")
  Trans_all <- read_csv(finput)
  
  Trans <- filter(Trans_all, Trans_all$StaffName==pers &
                    Trans_all$TransDateTime>=pStart & 
                    Trans_all$TransDateTime<=pEnd)
  Trans <- add_column(Trans, Week=week(Trans$TransDateTime))
```

### Person: `r pers`

### Time period: `r pStart` to `r pEnd`

## Consultations

__Total `r pers` consultations = `r count(Cons)`__

### Consultation Stories

```{r Cstories}
  Cstories <- select(Cons, ConsDate, Story) %>% filter(!is.na(Story))
  
  kable(Cstories, format="html")
```

### Consultation Notes

```{r Cnotes}
  Cnotes <- select(Cons, ConsDate, Notes) %>% filter(!is.na(Notes))
  
  kable(Cnotes, format="html")
```



## Presentations

__Total `r pers` presentations = `r count(Pres)`__

### Presentation Stories

```{r Pstories}
  Pstories <- select(Pres, PresDateTime, Story) %>% filter(!is.na(Story))
  
  kable(Pstories, format="html")
```

### Presentation Notes

```{r Pnotes}
  Pnotes <- select(Pres, PresDateTime, Notes) %>% filter(!is.na(Notes))
  
  kable(Pnotes, format="html")
```



## Transactions

__Total `r pers` transactions = `r count(Trans)`__

### Transaction Stories

```{r Tstories}
  Tstories <- select(Trans, TransDateTime, Story) %>% filter(!is.na(Story))
  
  kable(Tstories, format="html")
```

### Transaction Notes

```{r Tnotes}
  Tnotes <- select(Trans, TransDateTime, Notes) %>% filter(!is.na(Notes))
  
  kable(Tnotes, format="html")
```

